server:
  port: 8080

spring:
  resources:
    static-locations: classpath:/static/

logging:
  level:
    root: INFO
  file:
    name: logs/webssh.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
